/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controladores.ProductosJpaController;
import controladores.TiposProductosJpaController;
import controladores.TpvJpaController;
import controladores.exceptions.IllegalOrphanException;
import controladores.exceptions.NonexistentEntityException;
import dawfood.ModeloTabla;
import entidades.Productos;
import entidades.TiposProductos;
import entidades.Tpv;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JTable;

/**
 *
 * @author vickyfg
 */
public class Administrador extends javax.swing.JDialog {

    private static final EntityManagerFactory crud = Persistence.createEntityManagerFactory("com.mycompany_DawFoodVicky_jar_1.0-SNAPSHOTPU");
    private static final ProductosJpaController proJpa = new controladores.ProductosJpaController(crud);
    private static final TiposProductosJpaController tpJpa = new controladores.TiposProductosJpaController(crud);
    private static final TpvJpaController tpvJpa = new TpvJpaController(crud);
    private Principal principal;
    private List<Productos> lista = new ArrayList<>();

    /**
     * Creates new form Administrador
     */
    public Administrador(Principal parent, boolean model) {
        super(parent, model);
        principal = parent;
        lista = proJpa.findProductosEntities();
        initComponents();
        cargarDatosJTable();
    }

    public List<Productos> getLista() {
        return lista;
    }

    public void setLista(List<Productos> lista) {
        this.lista = lista;
    }

    public static List<Productos> crearListaProducto() {
        return proJpa.findProductosEntities();
    }

    //Método para incluir un producto en la 
    public static void incluirProducto(Productos nuevoProducto) throws Exception {
        proJpa.create(nuevoProducto);
    }

    //Método que recibe un int id para eliminar un producto de la bbdd
    public static void borrarProducto(int id) throws NonexistentEntityException, IllegalOrphanException {
        proJpa.destroy(id);
    }

    //Método que recibe un producto y usa el método edit para modificarlo
    public static void editarProducto(Productos productos) throws NonexistentEntityException, Exception {
        proJpa.edit(productos);
    }

    //Método que recibe una id y usa el método find para buscar por id
    public static Productos buscarPordId(int id) {
        return proJpa.findProductos(id);
    }

    //Método para buscar el nombre de tipo categoria producto 
     public TiposProductos buscarTipoProductoPorNombre(String nombreTipoProducto) {
        try {
            Query query = tpJpa.createNamedQuery("TiposProductos.findByCategoria");
            query.setParameter("categoria", nombreTipoProducto);
            return (TiposProductos) query.getSingleResult();
        } catch (Exception e) {
            // Manejo de excepciones en caso de que no se encuentre el tipo de producto
            // Puedes retornar null o lanzar una excepción personalizada, dependiendo de tu lógica de negocio
            return null;
        }
    }
    // Este método inserta los datos de la lista en el jtable
    private void cargarDatosJTable() {

        // Se crea el modelo de datos que contendrá el JTable
        // Este modelo se rellena de datos y luego se asocia al JTable
        ModeloTabla modelo = new ModeloTabla();

        // Array de object con el número de columnas del jtable
        // Para guardar cada campo de cada producto de la lista
        Object[] fila = new Object[modelo.getColumnCount()];

        // Iteramos por la lista y asignamos a
        // cada celda del array el valor del atributos del producto
        for (Productos producto : lista) {
            fila[0] = producto.getIdProducto();
            fila[1] = producto.getNombreProducto();
            fila[2] = producto.getPrecioProducto();
            fila[3] = producto.getIvaProducto();
            fila[4] = producto.getStockProducto();
            fila[5] = producto.getIdTipo().getCategoria();
            fila[6] = producto.getDescripcionProducto();
            modelo.addRow(fila);
        }
        // Agregamos esta fila a nuestro modelo
        modelo.addRow(fila);
        // Al finalizar el bucle el modelo tendrá tantas filas como nuestra lista

        // Decimos al JTable el modelo a usar
        jTable1.setModel(modelo);

    }

    // Método para obtener el jtable del formulario
    // desde el diálogo
    public JTable getJTable() {
        return this.jTable1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(227, 122, 110));
        jButton2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Nuevo PRODUCTO");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 122, 110)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformedGestion(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 240, 30));

        jButton3.setBackground(new java.awt.Color(227, 122, 110));
        jButton3.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Borrar");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 122, 110)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformedGestion(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 90, 30));

        jButton1.setBackground(new java.awt.Color(246, 235, 198));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, 100, -1));

        jButton4.setBackground(new java.awt.Color(227, 122, 110));
        jButton4.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Editar");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 122, 110)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformedGestion(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 80, 30));

        jTable1.setBackground(new java.awt.Color(255, 153, 153));
        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 204), 1, true));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Elija una opción para productos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 440, -1));

        jPanel1.setBackground(new java.awt.Color(246, 235, 198));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 460, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 490, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformedGestion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformedGestion
        new CrearNuevoProducto(this, true).setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformedGestion

    private void jButton3ActionPerformedGestion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformedGestion
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformedGestion

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Principal().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformedGestion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformedGestion
         new EditarProducto(this, true).setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformedGestion

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
