/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controladores.ProductosJpaController;
import controladores.exceptions.NonexistentEntityException;
import entidades.Productos;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Victoria
 */
public class EditarProducto extends javax.swing.JDialog {

    private Administrador admin;
    private Productos producto;
    private static final EntityManagerFactory emf = Persistence.createEntityManagerFactory("com.mycompany_DawFoodVicky_jar_1.0-SNAPSHOTPU");
    private static final ProductosJpaController proJpa = new controladores.ProductosJpaController(emf);

    /**
     * Creates new form EditarProducto
     */
    public EditarProducto(Administrador parent, boolean modal) {

        super(parent, modal);
        admin = parent;
        initComponents();
        mostrarDatosEditar();
        setLocationRelativeTo(null);
    }

    // Este método carga los datos 
    // de este jdialog del registro seleccionado en el jtable de la ventana
    private void mostrarDatosEditar() {

        //Obtengo la fila seleccionada y luego el id de esa fila
        int fila = filaSeleccionadaJTable(admin.getJTable());

        //Verifico que haya una fila seleccionada
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Para editar un producto debe seleccionar un producto de la lista", "DawFood", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Obtengo los valores de la fila seleccionada
        int idProducto = (int) admin.getJTable().getValueAt(fila, 0);
        producto = admin.buscarPordId(idProducto);

        jTextFieldId.setText(Integer.toString(producto.getIdProducto()));
         // Requisitos del proyecto id no editable
        jTextFieldId.setEditable(false);
        jTextFieldNombre.setText(producto.getNombreProducto());
        jTextFieldPrecio.setText(Double.toString(producto.getPrecioProducto()));
        jComboBoxIva.setSelectedItem(Integer.toString(producto.getIvaProducto()));
        jSpinnerStock.setValue(producto.getStockProducto());
        jTextAreaDescripcion.setText(producto.getDescripcionProducto());

        // Guarda producto seleccionado
        //Aqui se usa buscarporid que es un metodo NamedQuery
        this.producto = Administrador.buscarPordId(idProducto);
    }

    //Método que recibe un producto y usa el método edit para modificarlo
    public static void editarProducto(Productos producto) throws NonexistentEntityException, Exception {
        proJpa.edit(producto);
    }

    private int filaSeleccionadaJTable(JTable jTable1) {
        int fila = jTable1.getSelectedRow();
        return fila;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabe = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxIva = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabe1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabe2 = new javax.swing.JLabel();
        jSpinnerStock = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setBackground(new java.awt.Color(115, 172, 178));
        jButton7.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(246, 235, 198));
        jButton7.setText("Guardar");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(123, 169, 171)));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformedGestion(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 120, -1));

        jPanel1.setBackground(new java.awt.Color(123, 169, 171));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabe.setBackground(new java.awt.Color(153, 153, 153));
        jLabe.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabe.setForeground(new java.awt.Color(102, 102, 102));
        jLabe.setText("Editar producto ");
        jPanel1.add(jLabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 150, -1));

        jTextFieldId.setEditable(false);
        jTextFieldId.setBackground(new java.awt.Color(251, 234, 198));
        jTextFieldId.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 190, -1));

        jTextFieldPrecio.setBackground(new java.awt.Color(251, 234, 198));
        jTextFieldPrecio.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 190, -1));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(251, 234, 198));
        jLabel5.setText("Precio:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 80, 20));

        jComboBoxIva.setBackground(new java.awt.Color(251, 234, 198));
        jComboBoxIva.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxIva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "10", "21" }));
        jPanel1.add(jComboBoxIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 190, -1));

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(251, 234, 198));
        jLabel6.setText("Iva:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 80, 20));

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(251, 234, 198));
        jLabel7.setText("Stock:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 80, 20));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(251, 234, 198));
        jLabel3.setText("Descripición:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 140, 100));

        jLabe1.setBackground(new java.awt.Color(153, 153, 153));
        jLabe1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabe1.setForeground(new java.awt.Color(251, 234, 198));
        jLabe1.setText("Id:");
        jPanel1.add(jLabe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, -1));

        jTextFieldNombre.setBackground(new java.awt.Color(251, 234, 198));
        jTextFieldNombre.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 190, -1));

        jLabe2.setBackground(new java.awt.Color(153, 153, 153));
        jLabe2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabe2.setForeground(new java.awt.Color(251, 234, 198));
        jLabe2.setText("Nombre:");
        jPanel1.add(jLabe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, -1));

        jSpinnerStock.setName(""); // NOI18N
        jSpinnerStock.setNextFocusableComponent(jComboBoxIva);
        jSpinnerStock.setOpaque(true);
        jPanel1.add(jSpinnerStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 190, -1));

        jTextAreaDescripcion.setEditable(false);
        jTextAreaDescripcion.setBackground(new java.awt.Color(251, 234, 198));
        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 210, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 390, 460));

        jButton1.setBackground(new java.awt.Color(246, 235, 198));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 490, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformedGestion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformedGestion

        try {
            // Guardo en producto seleccionada los cambios de los jtextfiel   
            String nombre = jTextFieldNombre.getText();
            if (nombre.isEmpty()) {
                throw new IllegalArgumentException("El campo Nombre no puede estar vacio");
            }
            this.producto.setNombreProducto(jTextFieldNombre.getText());

            this.producto.setIvaProducto(Integer.parseInt(jComboBoxIva.getSelectedItem().toString()));

            int stock = (int) jSpinnerStock.getValue();
            if (stock <= 0) {
                throw new IllegalArgumentException("El campo Stock no puede ser cero");
            }
            this.producto.setStockProducto((int) jSpinnerStock.getValue());

            String precioS = jTextFieldPrecio.getText();
            if (precioS.isEmpty()) {
                throw new IllegalArgumentException("El campo Precio no puede estar vacio");
            }
            double precio = Double.parseDouble(precioS);
            if (precio < 0) {
                throw new IllegalArgumentException("El precio debe ser un número positivo");
            }
            this.producto.setPrecioProducto(Double.parseDouble(jTextFieldPrecio.getText()));

            this.producto.setDescripcionProducto(jTextAreaDescripcion.getText());

            editarProducto(this.producto);
            JOptionPane.showMessageDialog(null, "Registro modificado correctamente");
            this.dispose();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "DawFood", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al editar el producto", "DawFood", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButton7ActionPerformedGestion

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBoxIva;
    private javax.swing.JLabel jLabe;
    private javax.swing.JLabel jLabe1;
    private javax.swing.JLabel jLabe2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerStock;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
