/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controladores.ProductosJpaController;
import dawfood.Carrito;
import dawfood.ModeloTabla;
import entidades.Productos;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author vickyfg
 */
public class MostrarProducto extends javax.swing.JDialog {

    private List<Productos> listaComida = new ArrayList<>();
    private static final EntityManagerFactory emf = Persistence.createEntityManagerFactory("com.mycompany_DawFoodVicky_jar_1.0-SNAPSHOTPU");
    private static final ProductosJpaController proJpa = new controladores.ProductosJpaController(emf);
    private Carrito carrito = new Carrito();
    private Productos productoSeleccionado;

    /**
     * Creates new form MostrarProducto
     */
    public MostrarProducto(Principal parent, boolean model) {
        super(parent, model);
        initComponents();
        cargarDatosJTable();
        setLocationRelativeTo(null);
    }

    public List<Productos> getLista() {
        return listaComida;
    }

    public void setLista(List<Productos> lista) {
        this.listaComida = lista;
    }

    public static List<Productos> crearListas() {
        return proJpa.findProductosEntities();
    }

    private void cargarDatosJTable() {

        //Obtener la lista de productos filtrados por tipo 
        listaComida = crearListas().stream()
                .filter(p -> p.getIdTipo().getCategoria().equalsIgnoreCase("comida"))
                .collect(Collectors.toList());

        // Se crea el modelo de datos que contendrá el JTable
        // Este modelo se rellena de datos y luego se asocia al JTable
        ModeloTabla modelo = new ModeloTabla(true);

        for (Productos producto : listaComida) {
            Object[] fila = new Object[5];
            fila[0] = producto.getIdProducto();
            fila[1] = producto.getNombreProducto();
            fila[2] = producto.getPrecioProducto();
            fila[3] = producto.getIvaProducto();
            fila[4] = producto.getDescripcionProducto();

            modelo.addRow(fila);
        }

        jTable1.setModel(modelo);
    }

    public JTable getJTable() {
        return this.jTable1;
    }

    private void actualizarPrecioTotal() {
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto para calcular el precio.", "DawFood", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int idProdut = (int) jTable1.getValueAt(fila, 4);
        
        productoSeleccionado = listaComida.stream()
                .filter(p -> p.getIdProducto().equals(idProdut))
                .findFirst()
                .orElse(null);

        if (productoSeleccionado != null) {
            int cantidad = (int) jSpinnerCantidad.getValue();
            double precioTotal = productoSeleccionado.getPrecioProducto() * cantidad;
            jTextFieldPrecio.setText(Double.toString(precioTotal));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 153, 153));
        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Precio: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 110, -1));

        jTextFieldPrecio.setEditable(false);
        jTextFieldPrecio.setBackground(new java.awt.Color(246, 235, 198));
        jTextFieldPrecio.setFont(new java.awt.Font("Liberation Sans", 2, 18)); // NOI18N
        jTextFieldPrecio.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 110, -1));

        jButton1.setBackground(new java.awt.Color(246, 235, 198));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, 100, -1));

        jButton3.setBackground(new java.awt.Color(246, 235, 198));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Calcular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 100, -1));

        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));
        getContentPane().add(jSpinnerCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 110, -1));

        jTable1.setBackground(new java.awt.Color(110, 167, 176));
        jTable1.setForeground(new java.awt.Color(254, 244, 205));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 153, 153));
        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cantidad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 110, -1));

        jButton2.setBackground(new java.awt.Color(110, 167, 176));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Agregar al Carrito");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 200, 40));

        jLabel1.setBackground(new java.awt.Color(246, 235, 198));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 490, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        actualizarPrecioTotal();
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (productoSeleccionado != null) {
            int cantidad = (int) jSpinnerCantidad.getValue();
            double precioTotal = productoSeleccionado.getPrecioProducto() * cantidad;
            jTextFieldPrecio.setText(Double.toString(precioTotal));
            JOptionPane.showMessageDialog(this, "Producto agregado al carrito correctamente.", "DawFood", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        actualizarPrecioTotal();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
