/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controladores.ProductosJpaController;
import dawfood.Carrito;
import dawfood.ModeloTabla;
import entidades.Productos;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author vickyfg
 */
public class MostrarProductoP extends javax.swing.JDialog {

    private List<Productos> listaComida = new ArrayList<>();
    private static final EntityManagerFactory emf = Persistence.createEntityManagerFactory("com.mycompany_DawFoodVicky_jar_1.0-SNAPSHOTPU");
    private static final ProductosJpaController proJpa = new controladores.ProductosJpaController(emf);
    private Carrito carrito = Carrito.getCarrito();
    private Productos productoSeleccionado;

    /**
     * Creates new form MostrarProducto
     */
    public MostrarProductoP(Cliente parent, boolean model) {
        super(parent, model);
        initComponents();
        cargarDatosJTable();
        setLocationRelativeTo(null);
    }

    public List<Productos> getLista() {
        return listaComida;
    }

    public void setLista(List<Productos> lista) {
        this.listaComida = lista;
    }

    public static List<Productos> crearListas() {
        return proJpa.findProductosEntities();
    }

    private void cargarDatosJTable() {

        //Obtener la lista de productos filtrados por tipo 
        listaComida = crearListas().stream()
                .filter(p -> p.getIdTipo().getCategoria().equalsIgnoreCase("postre"))
                .collect(Collectors.toList());

        // Se crea el modelo de datos que contendrá el JTable
        // Este modelo se rellena de datos y luego se asocia al JTable
        ModeloTabla modelo = new ModeloTabla(false);

        for (Productos producto : listaComida) {
            Object[] fila = new Object[7];
            fila[0] = producto.getIdProducto();
            fila[1] = producto.getNombreProducto();
            fila[2] = producto.getPrecioProducto();
            fila[3] = producto.getIvaProducto();
            fila[4] = producto.getStockProducto();
            fila[5] = producto.getIdTipo().getCategoria();
            fila[6] = producto.getDescripcionProducto();
            modelo.addRow(fila);
        }

        jTable1.setModel(modelo);
    }

    public JTable getJTable() {
        return this.jTable1;
    }

    private void actualizarPrecioTotal() {
        try {
            final int porcentaje = 100;
            int fila = jTable1.getSelectedRow();
            if (fila == -1) {
                throw new IllegalArgumentException("Debe seleccionar un producto para calcular el precio.");
            }

            int idProducto = (int) jTable1.getValueAt(fila, 0);
            int stock = (int) jTable1.getValueAt(fila, 4);

            productoSeleccionado = listaComida.stream()
                    .filter(p -> p.getIdProducto().equals(idProducto))
                    .findFirst()
                    .orElse(null);

            int cantidad = (int) jSpinnerCantidad.getValue();
            if (cantidad < 1) {
                throw new IllegalArgumentException("Debe seleccionar una cantidad en positivo. Si desea borrar el producto vaya al carrito.");
            }
            if (cantidad > stock) {
                throw new IllegalArgumentException("No queda suficiente producto de lo que has elegido. Máximo " + stock);
            }

            double precioTotal = (((productoSeleccionado.getPrecioProducto() * productoSeleccionado.getIvaProducto()) / porcentaje) + productoSeleccionado.getPrecioProducto()) * cantidad;
            jTextFieldPrecio.setText(String.format("%.2f", precioTotal));

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "DawFood", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jButtonVCarrito = new javax.swing.JButton();
        jScrollTablaCompleta = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 153, 153));
        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Precio: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 110, -1));

        jTextFieldPrecio.setEditable(false);
        jTextFieldPrecio.setBackground(new java.awt.Color(246, 235, 198));
        jTextFieldPrecio.setFont(new java.awt.Font("Liberation Sans", 2, 18)); // NOI18N
        jTextFieldPrecio.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 110, -1));

        jButton1.setBackground(new java.awt.Color(246, 235, 198));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, 100, -1));

        jButton3.setBackground(new java.awt.Color(246, 235, 198));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Calcular IVA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 110, 30));

        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));
        getContentPane().add(jSpinnerCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 110, -1));

        jButtonVCarrito.setBackground(new java.awt.Color(110, 167, 176));
        jButtonVCarrito.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonVCarrito.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVCarrito.setText("Ver Carrito");
        jButtonVCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVCarritoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, 120, 40));

        jTable1.setBackground(new java.awt.Color(110, 167, 176));
        jTable1.setForeground(new java.awt.Color(254, 244, 205));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollTablaCompleta.setViewportView(jTable1);

        getContentPane().add(jScrollTablaCompleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 390));

        jLabel2.setBackground(new java.awt.Color(255, 153, 153));
        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cantidad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 110, -1));

        jButton2.setBackground(new java.awt.Color(110, 167, 176));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Agregar al Carrito");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, 200, 40));

        jLabel1.setBackground(new java.awt.Color(246, 235, 198));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 490, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        actualizarPrecioTotal();
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            final int obIva = 100;
            int fila = jTable1.getSelectedRow();
            if (fila == -1) {
                throw new IllegalArgumentException("Debe seleccionar un producto para calcular el precio.");
            }

            int idProducto = (int) jTable1.getValueAt(fila, 0);
            int stock = (int) jTable1.getValueAt(fila, 4);

            productoSeleccionado = listaComida.stream()
                    .filter(p -> p.getIdProducto().equals(idProducto))
                    .findFirst()
                    .orElse(null);

            int cantidad = (int) jSpinnerCantidad.getValue();
            if (cantidad < 1) {
                throw new IllegalArgumentException("Debe seleccionar una cantidad en positivo. Si desea borrar el producto vaya al carrito.");
            }
            if (cantidad > stock) {
                throw new IllegalArgumentException("No queda suficiente producto de lo que has elegido. Máximo " + stock);
            }
            carrito.agregarProducto(productoSeleccionado, cantidad);
            double precioTotal = (((productoSeleccionado.getPrecioProducto() * productoSeleccionado.getIvaProducto()) / obIva) + productoSeleccionado.getPrecioProducto()) * cantidad;
            jTextFieldPrecio.setText(String.format("%.2f", precioTotal));
            carrito.imprimirCarrito();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "DawFood", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        actualizarPrecioTotal();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonVCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVCarritoActionPerformed
        Cliente parent = (Cliente) this.getParent();
        new VerCarrito(parent, true).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVCarritoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonVCarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollTablaCompleta;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
