/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controladores.TpvJpaController;
import dawfood.Carrito;
import dawfood.GenerarTickets;
import dawfood.PasarelaDePago;
import dawfood.TarjetaCredito;
import entidades.DetalleTicket;
import entidades.Productos;
import entidades.Tickets;
import entidades.Tpv;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author Victoria
 */
public class Pagos extends javax.swing.JDialog {

    private static final EntityManagerFactory emf = Persistence.createEntityManagerFactory("com.mycompany_DawFoodVicky_jar_1.0-SNAPSHOTPU");
    private final TpvJpaController tpvController = new TpvJpaController(emf);
    private Tpv tpvActual;
    private double importeTotal;
    private double importeSubTotal;
    Carrito carrito = Carrito.getCarrito();
    private PasarelaDePago pasarelaDePago;

    public Pagos(Cliente parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.carrito = Carrito.getCarrito();
        this.pasarelaDePago = new PasarelaDePago();
        int idTpvActual = 154;
        tpvActual = obtenerTpvPorId(idTpvActual);
        this.importeTotal = importeTotal;
        this.importeSubTotal = importeSubTotal;

    }

    //NamedQuery
    public Tpv obtenerTpvPorId(int id) {
        return tpvController.findTpv(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabe = new javax.swing.JLabel();
        jTextField4Digitos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabe3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabe1 = new javax.swing.JLabel();
        jTextFieldAnyo = new javax.swing.JTextField();
        jTextFieldMes = new javax.swing.JTextField();
        jLabe2 = new javax.swing.JLabel();
        jLabe4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPasswordFieldCvv = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(110, 167, 176));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabe.setBackground(new java.awt.Color(153, 153, 153));
        jLabe.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabe.setForeground(new java.awt.Color(102, 102, 102));
        jLabe.setText("Tarjeta para el pago");
        jPanel1.add(jLabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 180, -1));

        jTextField4Digitos.setBackground(new java.awt.Color(251, 234, 198));
        jTextField4Digitos.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextField4Digitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 190, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("/");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(251, 234, 198));
        jLabel5.setText("CVV:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 80, 20));

        jLabe3.setBackground(new java.awt.Color(153, 153, 153));
        jLabe3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabe3.setForeground(new java.awt.Color(251, 234, 198));
        jLabe3.setText("digitos:");
        jPanel1.add(jLabe3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, -1));

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(251, 234, 198));
        jLabel6.setText("caducidad:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 110, 20));

        jLabe1.setBackground(new java.awt.Color(153, 153, 153));
        jLabe1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabe1.setForeground(new java.awt.Color(251, 234, 198));
        jLabe1.setText("4 últimos ");
        jPanel1.add(jLabe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, -1));

        jTextFieldAnyo.setBackground(new java.awt.Color(251, 234, 198));
        jTextFieldAnyo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextFieldAnyo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 80, -1));

        jTextFieldMes.setBackground(new java.awt.Color(251, 234, 198));
        jTextFieldMes.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextFieldMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 80, -1));

        jLabe2.setBackground(new java.awt.Color(153, 153, 153));
        jLabe2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabe2.setForeground(new java.awt.Color(251, 234, 198));
        jLabe2.setText("Fecha de ");
        jPanel1.add(jLabe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 120, -1));

        jLabe4.setBackground(new java.awt.Color(153, 153, 153));
        jLabe4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabe4.setForeground(new java.awt.Color(102, 102, 102));
        jLabe4.setText("Introduzca los datos de su ");
        jPanel1.add(jLabe4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 270, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Año");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 170, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Mes");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jPasswordFieldCvv.setBackground(new java.awt.Color(251, 234, 198));
        jPanel1.add(jPasswordFieldCvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 390, 320));

        jButton2.setBackground(new java.awt.Color(246, 235, 198));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Atrás");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, 100, -1));

        jButton3.setBackground(new java.awt.Color(110, 167, 176));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(251, 234, 198));
        jButton3.setText("Validar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 240, 50));

        jLabel1.setBackground(new java.awt.Color(246, 235, 198));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 490, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            validarDatosTarjeta();
        } catch (Exception ex) {
            Logger.getLogger(Pagos.class.getName()).log(Level.SEVERE, null, ex);
        }
        // this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void validarDatosTarjeta() throws Exception {
        String numTarjeta = jTextField4Digitos.getText();
        String cvv = new String(jPasswordFieldCvv.getPassword());
        String mesStr = jTextFieldMes.getText();
        String anyoStr = jTextFieldAnyo.getText();

        if (!validarNumTarjeta(numTarjeta)) {
            return;
        }

        if (!validarCVV(cvv)) {
            return;
        }

        if (!validarMesCaducidad(mesStr)) {
            return;
        }

        if (!validarAnyoCaducidad(anyoStr)) {
            return;
        }

        int mesCaducidad = Integer.parseInt(mesStr);
        int anyoCaducidad = Integer.parseInt(anyoStr);

        if (!compararFechaCaducidad(mesCaducidad, anyoCaducidad)) {
            return;
        }

        procesarPagoYGenerarTicket(numTarjeta, cvv, mesCaducidad, anyoCaducidad);
    }

    private boolean validarNumTarjeta(String numTarjeta) {
        if (!numTarjeta.matches("\\d{4}")) {
            JOptionPane.showMessageDialog(this, "Los últimos 4 dígitos de la tarjeta deben ser numéricos", "DawFood", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean validarCVV(String cvv) {
        if (!cvv.matches("\\d{3}")) {
            JOptionPane.showMessageDialog(this, "El CVV debe ser un número de 3 dígitos", "DawFood", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean validarMesCaducidad(String mesStr) {
        if (!mesStr.matches("(0[1-9]|1[0-2])")) {
            JOptionPane.showMessageDialog(this, "El mes debe ser un número entre 01 y 12", "DawFood", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean validarAnyoCaducidad(String anyoStr) {
        if (!anyoStr.matches("\\d{4}")) {
            JOptionPane.showMessageDialog(this, "El año debe ser un número de 4 dígitos", "DawFood", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean compararFechaCaducidad(int mesCaducidad, int anyoCaducidad) {
        LocalDate fechaActual = LocalDate.now();
        int mesActual = fechaActual.getMonthValue();
        int anyoActual = fechaActual.getYear();

        if (anyoCaducidad < anyoActual || (anyoCaducidad == anyoActual && mesCaducidad < mesActual)) {
            JOptionPane.showMessageDialog(this, "La tarjeta está caducada", "DawFood", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void procesarPagoYGenerarTicket(String numTarjeta, String cvv, int mesCaducidad, int anyoCaducidad) throws Exception {
        TarjetaCredito tarjetaValida = null;

        for (TarjetaCredito tarjeta : pasarelaDePago.getTarjetas().keySet()) {
            if (tarjeta.getNumTarjeta().endsWith(numTarjeta)
                    && tarjeta.getCvv().equals(cvv)
                    && tarjeta.getMesCaducidad() == mesCaducidad
                    && tarjeta.getAnyoCaducidad() == anyoCaducidad) {
                tarjetaValida = tarjeta;
                break;
            }
        }

        if (tarjetaValida != null) {
            // Calcular importes
            double importeTotal = 0.0;
            double importeSubTotal = 0.0;

            for (Map.Entry<Productos, Integer> producto : carrito.getProductosCarrito().entrySet()) {
                double precioProducto = producto.getKey().getPrecioProducto();
                double precioProductoConIva = precioProducto + ((precioProducto * producto.getKey().getIvaProducto()) / 100);
                importeTotal += precioProductoConIva * producto.getValue();
                importeSubTotal += precioProducto * producto.getValue();
            }

           
            Tickets ticket = GenerarTickets.generarNuevoTicket(importeTotal, importeSubTotal, tpvActual, carrito);
            String textoTicket = GenerarTickets.generarTextoTicket(
                    ticket.getIdTicket(),
                    ticket.getFechaTicket(),
                    ticket.getHoraTicket(),
                    importeTotal,
                    ticket.getCodTransaccion(),
                    carrito
            );

           
            JOptionPane.showMessageDialog(this, textoTicket, "Ticket Generado", JOptionPane.INFORMATION_MESSAGE);

            
            carrito.limpiarCarrito();
            
            new Principal().setVisible(true);

            
//            Cliente parent = (Cliente) this.getParent();
//            new VerCarrito(parent, true).setVisible(true);
            this.dispose();
        } else {
            
            JOptionPane.showMessageDialog(this, "Datos de tarjeta no válidos", "DawFood", JOptionPane.ERROR_MESSAGE);
            
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabe;
    private javax.swing.JLabel jLabe1;
    private javax.swing.JLabel jLabe2;
    private javax.swing.JLabel jLabe3;
    private javax.swing.JLabel jLabe4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldCvv;
    private javax.swing.JTextField jTextField4Digitos;
    private javax.swing.JTextField jTextFieldAnyo;
    private javax.swing.JTextField jTextFieldMes;
    // End of variables declaration//GEN-END:variables
}
