/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import dawfood.Carrito;
import javax.swing.JOptionPane;

/**
 *
 * @author Victoria
 */
public class VerCarrito extends javax.swing.JDialog {

    private Carrito carrito = Carrito.getCarrito();
    private Cliente parent;

    /**
     * Creates new form VerCarrito
     */
    public VerCarrito(Cliente parent, boolean model) {
        super(parent, model);
        this.parent = parent;
        initComponents();
        verCarrito();
        setLocationRelativeTo(null);

    }

    private void verCarrito() {
        String carritoTexto = carrito.imprimirCarrito();
        jTextAreaVistaCarrito.setText(carritoTexto);
        double totalIVA = carrito.getTotalIva();
        jTextFieldTotal.setText(String.format("%.2f", totalIVA));
        String totalCarrito = carrito.calcularTotalCarrito();
        jTextFieldTotal1.setText(String.valueOf(totalCarrito));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNC = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonPago = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTotal1 = new javax.swing.JTextField();
        jButtonVaciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaVistaCarrito = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaVistaCarrito1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNC.setBackground(new java.awt.Color(217, 163, 156));
        jButtonNC.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonNC.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNC.setText("Nuevo cliente");
        jButtonNC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 122, 110)));
        jButtonNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNCActionPerformedGestion(evt);
            }
        });
        getContentPane().add(jButtonNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, 170, 50));

        jLabel3.setBackground(new java.awt.Color(255, 153, 153));
        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("€");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 30, -1));

        jLabel5.setBackground(new java.awt.Color(255, 153, 153));
        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Iva");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 110, -1));

        jButton1.setBackground(new java.awt.Color(246, 235, 198));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, 100, -1));

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setBackground(new java.awt.Color(246, 235, 198));
        jTextFieldTotal.setFont(new java.awt.Font("Liberation Sans", 2, 18)); // NOI18N
        jTextFieldTotal.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 110, -1));

        jLabel4.setBackground(new java.awt.Color(255, 153, 153));
        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Total");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 110, -1));

        jButtonPago.setBackground(new java.awt.Color(227, 122, 110));
        jButtonPago.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonPago.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPago.setText("Ir al pago");
        jButtonPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 122, 110)));
        jButtonPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagoActionPerformedGestion(evt);
            }
        });
        getContentPane().add(jButtonPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 150, 50));

        jLabel6.setBackground(new java.awt.Color(255, 153, 153));
        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("€");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 30, -1));

        jTextFieldTotal1.setEditable(false);
        jTextFieldTotal1.setBackground(new java.awt.Color(246, 235, 198));
        jTextFieldTotal1.setFont(new java.awt.Font("Liberation Sans", 2, 18)); // NOI18N
        jTextFieldTotal1.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotal1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 110, -1));

        jButtonVaciar.setBackground(new java.awt.Color(227, 122, 110));
        jButtonVaciar.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonVaciar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVaciar.setText("Vaciar carrito");
        jButtonVaciar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 122, 110)));
        jButtonVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVaciarActionPerformedGestion(evt);
            }
        });
        getContentPane().add(jButtonVaciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 160, 50));

        jTextAreaVistaCarrito.setEditable(false);
        jTextAreaVistaCarrito.setBackground(new java.awt.Color(186, 214, 217));
        jTextAreaVistaCarrito.setColumns(20);
        jTextAreaVistaCarrito.setRows(5);
        jScrollPane1.setViewportView(jTextAreaVistaCarrito);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 270, 230));

        jTextAreaVistaCarrito1.setEditable(false);
        jTextAreaVistaCarrito1.setBackground(new java.awt.Color(186, 214, 217));
        jTextAreaVistaCarrito1.setColumns(20);
        jTextAreaVistaCarrito1.setRows(5);
        jScrollPane2.setViewportView(jTextAreaVistaCarrito1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 270, 320));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 490, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVaciarActionPerformedGestion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVaciarActionPerformedGestion
        carrito.limpiarCarrito();
        JOptionPane.showMessageDialog(this, "Se vació el carrito", "DawFood", JOptionPane.ERROR_MESSAGE);
        this.dispose();
        return;
    }//GEN-LAST:event_jButtonVaciarActionPerformedGestion

    private void jButtonPagoActionPerformedGestion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagoActionPerformedGestion
        if (carrito.getProductosCarrito().isEmpty()) {
        JOptionPane.showMessageDialog(this, "El carrito esta vacio", "DawFood", JOptionPane.ERROR_MESSAGE);
        return;
    }
        this.dispose();
        new Pagos(parent, true).setVisible(true);
        return;
    }//GEN-LAST:event_jButtonPagoActionPerformedGestion

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed

    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotal1ActionPerformed

    private void jButtonNCActionPerformedGestion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNCActionPerformedGestion
        this.dispose();
        new Principal().setVisible(true);


    }//GEN-LAST:event_jButtonNCActionPerformedGestion

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonNC;
    private javax.swing.JButton jButtonPago;
    private javax.swing.JButton jButtonVaciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaVistaCarrito;
    private javax.swing.JTextArea jTextAreaVistaCarrito1;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldTotal1;
    // End of variables declaration//GEN-END:variables
}
